name: Group 19 Unity activation file

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  activation:
    name: Request Unity manual activation file
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload manual activation file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          if-no-files-found: error
          retention-days: 1
